version = "0.1.4"
slug = "lumino"
bundle = [
    "/docs/README.pdf",
    "/tests",
    "/fixtures",
    "/media/avatars/example*.jpg",
    "/media/avatars/noavatar.png",
    "/factories",
    "/.gitignore",
    "/pyproject.toml",
    "/uv.lock",
    "/justfile",
    "/pytest.ini",
]
backup_on_update = ["justfile"]
delete_on_update = ["tests/test_login_required.py"]
exclude_from_zip = [
    "*.pyc",
    ".DS_Store",
    "/.git",
    "*.bak",
    ".venv",
    ".env",
    "/media",
    "*cache*"
]
test_cmd = "uv run pytest"

[release_notes]
"0.1.0" = "Primera versión"
"0.1.1" = "Actualización de tests"
"0.1.2" = "Actualización de tests"
"0.1.3" = "Corrige tests login_required"
"0.1.4" = "Ignora carpetas cache al crear el zip"
